export enum RequestsType {
  CREATED = 'CREATED',
  CANCELED = 'CANCELED',
  CANCELED_REQUESTED = 'CANCELED_REQUESTED',
  EDITED = 'EDITED',
  REJECTED = 'REJECTED',
  APPROVED = 'APPROVED',
  PEOPLE_REQUESTED  = 'PEOPLE_REQUESTED',
  PAYMENT_REQUESTED = 'PAYMENT_REQUESTED',
  PEOPLE_SENT = 'PEOPLE_SENT',
  PAYMENT_SENT = 'PAYMENT_SENT',
  PAYMENT_REJECTED = 'PAYMENT_REJECTED',
}

export enum ProfessorRequestsType {
  DOCUMENT_REQUESTED = 'DOCUMENT_REQUESTED',
  DOCUMENT_APPROVED = 'DOCUMENT_APPROVED',
  DOCUMENT_REJECTED = 'DOCUMENT_REJECTED'
}